name: hw1_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - torchvision
  - pytorch
  - nest-asyncio
  - python-dateutil
  - six
  - readline
  - tk
  - pygments
  - jupyter_client
  - wcwidth
  - pickleshare
  - backcall
  - debugpy
  - matplotlib-inline
  - openssl
  - ptyprocess
  - pexpect
  - setuptools
  - jupyter_core
  - sqlite
  - wheel
  - pure_eval
  - ipython
  - libcxx
  - zeromq
  - decorator
  - ca-certificates
  - pip
  - prompt-toolkit
  - stack_data
  - libsodium
  - entrypoints
  - ncurses
  - zlib
  - bzip2
  - certifi
  - traitlets
  - pyzmq
  - executing
  - appnope
  - xz
  - asttokens
  - tornado
  - jedi
  - parso
  - tzdata
  - libffi
  - ipykernel
  - matplotlib
  - pandas
  - scipy
  - tqdm
  - xgboost
